---
- name: ios configuration
  hosts: router_pass_ssh

  tasks:
    - name: show the username
      debug:
        msg: "{{ansible_user}}"

    - name: config from external file
      ios_config:
        src: interface_config.txt
        diff_against: startup
        save_when: modified

    - name:
      ios_facts:
        gather_subset: all

    - debug:
        msg: "{{ ansible_net_interfaces }}"
